export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const FORGOT_PASS = 'FORGOT_PASS';
export const FORGOT_PASS_REQUEST = 'FORGOT_PASS_REQUEST';
export const FORGOT_PASS_SUCCESS = 'FORGOT_PASS_SUCCESS';
export const FORGOT_PASS_FAILURE = 'FORGOT_PASS_FAILURE';

export const RESET_PASS = 'RESET_PASS';
export const RESET_PASS_REQUEST = 'RESET_PASS_REQUEST';
export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS';
export const RESET_PASS_FAILURE = 'RESET_PASS_FAILURE';

export const LOG_OUT = 'LOG_OUT';

export const SEND_CONFIRM_EMAIL = 'SEND_CONFIRM_EMAIL';

export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_FORGOT_PASS_MODAL = 'OPEN_FORGOT_PASS_MODAL';
export const CLOSE_FORGOT_PASS_MODAL = 'CLOSE_FORGOT_PASS_MODAL';
export const OPEN_RESET_PASS_MODAL = 'OPEN_RESET_PASS_MODAL';
export const CLOSE_RESET_PASS_MODAL = 'CLOSE_RESET_PASS_MODAL';
